# Generated by Django 3.0.6 on 2020-05-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20200522_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='user',
        ),
    ]
