# Generated by Django 3.0.6 on 2020-05-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_todomodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='discription',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='date',
            field=models.DateField(),
        ),
    ]
