# Generated by Django 3.0.6 on 2020-05-29 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_auto_20200529_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscriptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription_summary', models.TextField()),
                ('taskId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to='todoapp.ToDoModel')),
            ],
        ),
    ]
