# Generated by Django 3.0.6 on 2020-05-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_discriptionmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscriptionModel',
            new_name='SummaryModel',
        ),
    ]
