# Generated by Django 3.0.6 on 2020-05-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_auto_20200529_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarymodel',
            name='dateTime',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
