# Generated by Django 3.0.6 on 2020-05-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_summarymodel_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarymodel',
            name='modefied',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
