# Generated by Django 3.0.6 on 2020-05-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0011_auto_20200530_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('inProgress', 'In progress'), ('done', 'Done')], default='todo', max_length=60),
        ),
    ]
