# Generated by Django 3.0.6 on 2020-05-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0012_todomodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('inProgress', 'In progress'), ('done', 'Done')], default='inProgress', max_length=60),
        ),
    ]
