# Generated by Django 3.0.6 on 2020-05-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0014_auto_20200530_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='flag',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
