# Generated by Django 3.0.6 on 2020-05-31 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0015_todomodel_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='flag',
        ),
    ]
