# Generated by Django 3.0.6 on 2020-05-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0016_remove_todomodel_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarymodel',
            name='discription_summary',
            field=models.TextField(default=None),
        ),
    ]
