# Generated by Django 3.0.6 on 2020-05-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0017_auto_20200531_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarymodel',
            name='discription_summary',
            field=models.TextField(default='None'),
        ),
    ]
