# Generated by Django 3.0.6 on 2020-06-17 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0018_auto_20200531_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summarymodel',
            old_name='discription_summary',
            new_name='description_summary',
        ),
        migrations.RenameField(
            model_name='todomodel',
            old_name='discription',
            new_name='description',
        ),
    ]
