# Generated by Django 3.0.7 on 2020-06-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0019_auto_20200617_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='flagTask',
            field=models.CharField(default='no', max_length=60),
        ),
    ]
